<?php

namespace App\Http\Controllers\VouchersControllers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-29 at 18:24:55.
 */
class VirtualVouchersControllerTest extends \TestCase {

    /**
     * @var VirtualVouchersController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setUp();
        $this->object = new VirtualVouchersController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        parent::tearDown();
    }

    /**
     * @covers App\Http\Controllers\VouchersControllers\VirtualVouchersController::showVirtualVoucherImage
     * @todo   Implement testShowVirtualVoucherImage().
     */
    public function testShowVirtualVoucherImage() {
        $result1 = $this->object->showVirtualVoucherImage('12345');
        $this->assertEquals($result1, 'Invalid code or not found Image');
    }

}
